name: Upstream Sync
permissions:
  contents: write
on:
  schedule:
    - cron: '0 0/6 * * *' # UTCæ—¶é—´æ¯6å°æ—¶åŒæ­¥ä¸€æ¬¡
  workflow_dispatch: # å…è®¸æ‰‹åŠ¨è§¦å‘
jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }} # åªåœ¨forkä»“åº“è¿è¡Œ
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: https://github.com/LmeSzinc/AzurLaneAutoScript/ # ğŸ› ï¸ä¿®æ”¹ä¸ºä¸Šæ¸¸ä»“åº“
          upstream_sync_branch: master # ğŸ› ï¸ä¸Šæ¸¸åˆ†æ”¯åï¼Œå¦‚ï¼šmain, master
          target_sync_branch: master # ğŸ› ï¸ä½ è¦åŒæ­¥çš„æœ¬åœ°åˆ†æ”¯å
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
